"""
Generate customized tiny11 PowerShell scripts based on user selections.
"""
from pathlib import Path
from dataclasses import dataclass, field
from .ps_parser import AppxPackage, RegistryTweak, SystemPackage


@dataclass
class BuildConfig:
    """User's build configuration."""
    mode: str = "regular"  # "regular" or "core"
    iso_drive: str = ""     # e.g. "E"
    scratch_drive: str = "" # e.g. "D", empty = use script dir
    enabled_packages: list[str] = field(default_factory=list)
    enabled_tweaks: list[str] = field(default_factory=list)
    enabled_system_packages: list[str] = field(default_factory=list)
    enable_dotnet35: bool = False


def generate_script(
    config: BuildConfig,
    template_path: Path,
    all_packages: dict[str, list[AppxPackage]],
    all_tweaks: dict[str, list[RegistryTweak]],
    all_system_packages: list[SystemPackage],
) -> str:
    """Generate a customized PS1 script."""
    template = template_path.read_text(encoding="utf-8")
    
    # Build the package prefixes string
    selected_prefixes = []
    for pkg in all_packages.get("regular", []):
        if pkg.prefix in config.enabled_packages:
            selected_prefixes.append(f"'{pkg.prefix}'")
    if config.mode == "core":
        for pkg in all_packages.get("core_only", []):
            if pkg.prefix in config.enabled_packages:
                selected_prefixes.append(f"'{pkg.prefix}'")
    
    package_block = ",\n".join(f"{p}" for p in selected_prefixes)
    
    # Build tweaks block
    tweaks_block = _build_tweaks_block(config, all_tweaks)
    
    # Build system packages block (Core only)
    sys_pkg_block = ""
    if config.mode == "core" and config.enabled_system_packages:
        sys_pkg_block = _build_system_packages_block(config, all_system_packages)
    
    # Generate the script
    script = _generate_full_script(config, package_block, tweaks_block, sys_pkg_block)
    return script


def _build_tweaks_block(config: BuildConfig, all_tweaks: dict[str, list[RegistryTweak]]) -> str:
    """Build the registry tweaks section."""
    lines = []
    for category, tweaks in all_tweaks.items():
        category_enabled = any(t.description in config.enabled_tweaks for t in tweaks)
        if not category_enabled:
            continue
        lines.append(f'Write-Output "{category}:"')
        for tweak in tweaks:
            if tweak.description in config.enabled_tweaks:
                esc_path = tweak.path.replace("\\", "\\\\")
                lines.append(
                    f"Set-RegistryValue '{tweak.path}' '{tweak.name}' '{tweak.value}' '{tweak.value}'"
                )
    return "\n".join(lines)


def _build_system_packages_block(config: BuildConfig, packages: list[SystemPackage]) -> str:
    """Build the system packages removal block."""
    lines = []
    for pkg in packages:
        if pkg.display_name in config.enabled_system_packages:
            lines.append(f'    "{pkg.pattern}",')
    if not lines:
        return ""
    return "$packagePatterns = @(\n" + "\n".join(lines) + "\n)"


def generate_command(config: BuildConfig, script_dir: Path) -> str:
    """Generate the PowerShell command to run."""
    script_name = "tiny11maker.ps1" if config.mode == "regular" else "tiny11Coremaker.ps1"
    script_path = script_dir / script_name
    
    args = []
    if config.iso_drive:
        args.append(f"-ISO {config.iso_drive}")
    if config.scratch_drive:
        args.append(f"-SCRATCH {config.scratch_drive}")
    
    arg_str = " ".join(args)
    
    return (
        f'Set-ExecutionPolicy Bypass -Scope Process; '
        f'& "{script_path}" {arg_str}'
    )


def generate_elevated_command(config: BuildConfig, script_dir: Path) -> str:
    """Generate a command that launches elevated PowerShell."""
    script_name = "tiny11maker.ps1" if config.mode == "regular" else "tiny11Coremaker.ps1"
    script_path = script_dir / script_name
    
    args = []
    if config.iso_drive:
        args.append(f"-ISO {config.iso_drive}")
    if config.scratch_drive:
        args.append(f"-SCRATCH {config.scratch_drive}")
    
    arg_str = " ".join(args)
    ps_cmd = f'Set-ExecutionPolicy Bypass -Scope Process; & "{script_path}" {arg_str}'
    
    # This will be used with ShellExecuteW to run elevated
    return ps_cmd


def _generate_full_script(config: BuildConfig, packages: str, tweaks: str, sys_pkgs: str) -> str:
    """Generate a full customized script (for preview/download)."""
    mode_label = "Regular" if config.mode == "regular" else "Core"
    
    script = f'''# tiny11 Builder - Custom {mode_label} Script
# Generated by tiny11 Builder GUI
# Mode: {mode_label}
# ISO Drive: {config.iso_drive or "(auto)"}
# Scratch Drive: {config.scratch_drive or "(script dir)"}

param (
    [ValidatePattern('^[c-zC-Z]$')][string]$ISO,
    [ValidatePattern('^[c-zC-Z]$')][string]$SCRATCH
)

if (-not $SCRATCH) {{
    $ScratchDisk = $PSScriptRoot -replace '[\\\\]+$', ''
}} else {{
    $ScratchDisk = $SCRATCH + ":"
}}

# --- Package Prefixes ---
$packagePrefixes = {packages}

# --- The rest of the script follows the original tiny11builder flow ---
# (See tiny11maker.ps1 / tiny11Coremaker.ps1 for the full implementation)
# This is a CONFIG PREVIEW - the actual build uses the original script
# with your selections applied via the GUI.
'''
    return script
